export const ourProductArray = [
    {
      discountBtn: false,
      discountPrice: 40,
      trashIcon: false,
      heartIcon: true,
      eyeIcon: true,
      src: "/image/dog-img.svg",
      Heading: "Breed Dry Dog Food",
      price: 100,
      star: 3,
      reviews: 35,
      colorDiv: false,
     
    },
    {
        discountBtn: false,
        discountPrice: 40,
        trashIcon: false,
        heartIcon: true,
        eyeIcon: true,
         src: "/image/camera-img.svg",
        Heading: "CANON EOS DSLR Camera",
        price: 360,
        star: 4,
        reviews: 95,
        colorDiv: false,
      },
      {
        discountBtn: false,
        discountPrice: 40,
        trashIcon: false,
        heartIcon: true,
        eyeIcon: true,
        src: "/image/laptop-img.svg",
        Heading: "ASUS FHD Gaming Laptop",
        price: 700,
        star: 5,
        reviews: 325,
        colorDiv: false,
      },
      {
        discountBtn: false,
        discountPrice: 40,
        trashIcon: false,
        heartIcon: true,
        eyeIcon: true,
        src: "/image/product-img.jpg",
        Heading: "Curology Product Set ",
        price: 500,
        star: 4,
        reviews: 145,
        colorDiv: false,
      
      },
      {
        discountBtn: true,
        discountPrice: "new",
        trashIcon: false,
        heartIcon: true,
        eyeIcon: true,
        src: "/image/kidsredcar-img.svg",
        Heading: "Kids Electric Car",
        price: 960,
        star: 5,
        reviews: 65,
        colorDiv: true,
        color1: "bg-black",
        color2: "red"
        
      },
      {
        discountBtn: false,
        discountPrice: 40,
        trashIcon: false,
        heartIcon: true,
        eyeIcon: true,
        src: "/image/yellowshoes-img.svg",
        Heading: "Jr. Zoom Soccer Cleats",
        price: 1160,
        star: 5,
        reviews: 35,
        colorDiv: true,
        color1: "bg-black",
        color2: "red"
      },
      {
        discountBtn: true,
        discountPrice: "new",
        trashIcon: false,
        heartIcon: true,
        eyeIcon: true,
        src: "/image/gp11-img.svg",
        Heading: "GP11 Shooter USB Gamepad",
        price: 660,
        star: 4,
        reviews: 55,
        colorDiv: true,
        color1: "bg-black",
        color2: "red"
      },
      {
        discountBtn: false,
        discountPrice: 40,
        trashIcon: false,
        heartIcon: true,
        eyeIcon: true,
        src: "/image/greencoat-img.svg",
        Heading: "Quilted Satin Jacket",
        price: 660,
        star: 5,
        reviews: 55,
        colorDiv: true,
        color1: "bg-black",
        color2: "red",
      }
  ]